; =============================================================
; OPcache-настройки под Bitrix24
; (см. рекомендации https://dev.1c-bitrix.ru/learning/course/?COURSE_ID=37&LESSON_ID=8849)
; =============================================================
[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 50000
opcache.revalidate_freq = 2
opcache.validate_timestamps = 1
opcache.fast_shutdown = 1
opcache.save_comments = 1
opcache.load_comments = 1
opcache.huge_code_pages = 0
opcache.jit = tracing
opcache.jit_buffer_size = 128M
